/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javafxapplication1;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Idrees
 */
public class SimulationTable extends javax.swing.JFrame {

    /**
     * Creates new form SimulationTable
     */
     DefaultTableModel model;
    public SimulationTable(TableRow[]  simtable) {
        initComponents();
        
        this.setTitle("EventDetails");
          model= (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
       
        for (TableRow t1 : simtable) {
        Object row[]={t1.dayno,t1.InitialInventory,t1.Demand,t1.InventoryLevel,t1.Z,t1.SalesRevenue,t1.OrderCost,t1.HolidingCost,t1.PenaltyCost,t1.TotalRevenue};
        model.addRow(row);
        }
        model.fireTableDataChanged();
        model.setRowCount(simtable.length);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Day", "Initial Inventroy ", "Demand", "Final Inventory ", "Items Ordered", "Sales Revenue", "Ordering Cost", "HoldingCost", "Penalty Cost", "Total Revenue"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    void getGraph(TableRow[] table){
         Color[] c = new Color[]{new Color(0x0587D9)};
            com.objectplanet.chart.BarChart chartqt = new com.objectplanet.chart.BarChart();
            String[] xaxis=new String[table.length];
            double[] yaxis=new double[table.length];
            int i=0;
            int maxD=0;
            
            for (TableRow t : table) {
                xaxis[i]=""+(t.dayno);
                yaxis[i]=t.Demand;
                if(t.Demand>maxD)
                    maxD=t.Demand;
                i++;
                
            
        }
             

            chartqt.setSampleCount(xaxis.length);
            chartqt.setSampleValues(0, yaxis);
            chartqt.setSampleColors(c);
            chartqt.setBackground(Color.white);
            chartqt.set3DModeOn(true);
            chartqt.set3DDepth(5);
            chartqt.setRange(0,maxD);
            chartqt.setFont("sampleLabelFont", new Font("Arial", Font.BOLD, 12));
            chartqt.setBarLabels(xaxis);
            
            chartqt.setBarLabelsOn(true);
            chartqt.setLabelAngle("barLabelAngle", 270);
            chartqt.setValueLabelsOn(true);
            chartqt.setValueLabelStyle(com.objectplanet.chart.Chart.OUTSIDE);

           Frame f = new Frame();
            f.setTitle("D(t)");
            f.setSize(400, 300);
            f.add("Center", chartqt);
            f.setVisible(true);

           
           
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //    new SimulationTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
